# Generated by Django 3.2.3 on 2021-06-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210622_0230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bids',
        ),
        migrations.AddField(
            model_name='listing',
            name='item_name',
            field=models.CharField(default='test', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
