# Generated by Django 3.2.3 on 2021-06-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210624_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='item_description',
            field=models.CharField(default='description', max_length=1000),
        ),
        migrations.AddField(
            model_name='listing',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item_name',
            field=models.CharField(default='name', max_length=120),
        ),
    ]
