# Generated by Django 3.2.3 on 2021-06-28 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210628_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_item', to='auctions.listing')),
                ('item_bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_bids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
