# Generated by Django 3.2.3 on 2021-06-29 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_owner', to=settings.AUTH_USER_MODEL)),
                ('watch_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_watching', to='auctions.listing')),
            ],
        ),
    ]
