# Generated by Django 3.2.3 on 2021-06-29 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_item', to='auctions.listing')),
                ('user_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
