# Generated by Django 3.2.3 on 2021-06-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listing_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='item_category',
            field=models.CharField(default='', max_length=64),
        ),
    ]
